import { CO2eFactorFuel, Refrigerant } from '../types';

// ============================================================================
// GHG_EmissionFactor.csv 기반 배출계수 (온실가스 배출권거래제 지침 2024)
// ============================================================================
// GWP 기준: IPCC AR5 (CO2=1, CH4=21, N2O=310)
// 산정식: CO2e = 활동량 × 순발열량 × (CO2 + CH4×21 + N2O×310) / 10^6
// ============================================================================

export const STATIONARY_FUELS: CO2eFactorFuel[] = [
  // ========== 기체 연료 (Gaseous Fuels) ==========
  {
    name: 'City Gas (LNG)',
    translationKey: 'naturalGas',
    units: ['Nm3', 'MJ'],
    factors: { 'Nm3': 2.18474, 'MJ': 0.05617 }, // 38.9 * (56100 + 1*21 + 0.1*310) / 10^6
    // 상세 산정 근거 - 제조업 부문 기준
    netHeatingValue: 38.9,
    heatingValueUnit: 'MJ/Nm3',
    co2EF: 56100,
    ch4EF: 1,  // 제조업 부문 (에너지산업:1, 상업/가정:5)
    n2oEF: 0.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:5',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  {
    name: 'LPG (Propane)',
    translationKey: 'propane',
    units: ['kg', 'Nm3'],
    factors: { 'kg': 2.92412, 'Nm3': 2.14936 }, // 46.3 * (63100 + 1*21 + 0.1*310) / 10^6
    netHeatingValue: 46.3,
    heatingValueUnit: 'MJ/kg',
    co2EF: 63100,
    ch4EF: 1,  // 제조업 부문 (에너지산업:1, 상업/가정:5)
    n2oEF: 0.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:6',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  {
    name: 'LPG (Butane)',
    translationKey: 'butane',
    units: ['kg'],
    factors: { 'kg': 2.88989 },
    netHeatingValue: 45.7,
    heatingValueUnit: 'MJ/kg',
    co2EF: 63100,
    ch4EF: 1,
    n2oEF: 0.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:38',
    source: '온실가스 배출권거래제 지침 (2024)',
  },

  {
    name: 'Natural Gas (kg)',
    translationKey: 'naturalGasKg',
    units: ['kg'],
    factors: { 'kg': 2.77257 }, // 49.4 * (56100 + 1*21 + 0.1*310) / 10^6
    netHeatingValue: 49.4,
    heatingValueUnit: 'MJ/kg',
    co2EF: 56100,
    ch4EF: 1,  // 제조업 부문 (에너지산업:1, 상업/가정:5)
    n2oEF: 0.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:13',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  // ========== 액체 연료 (Liquid Fuels) ==========
  {
    name: 'Diesel',
    translationKey: 'diesel',
    units: ['liters', 'gal'],
    factors: { 'liters': 2.61708, 'gal': 9.91874 }, // gal = 2.61708 × 3.79
    netHeatingValue: 35.2,
    heatingValueUnit: 'MJ/L',
    co2EF: 74100,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:37',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Gasoline',
    translationKey: 'gasoline',
    units: ['liters', 'gal'],
    factors: { 'liters': 2.19807, 'gal': 8.33069 }, // gal = 2.19807 × 3.79
    netHeatingValue: 30.4,
    heatingValueUnit: 'MJ/L',
    co2EF: 69300,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:36',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Kerosene (Heating Oil)',
    translationKey: 'heatingOilDiesel',
    units: ['liters', 'gal'],
    factors: { 'liters': 2.46750, 'gal': 9.35183 }, // gal = 2.46750 × 3.79
    netHeatingValue: 34.2,
    heatingValueUnit: 'MJ/L',
    co2EF: 71900,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:등유',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'B-C Oil',
    translationKey: 'heavyFuelOil',
    units: ['liters'],
    factors: { 'liters': 3.04384 },
    netHeatingValue: 39.2,
    heatingValueUnit: 'MJ/L',
    co2EF: 77400,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:B-C유',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'B-A Oil',
    translationKey: 'lightFuelOil',
    units: ['liters'],
    factors: { 'liters': 2.73517 },
    netHeatingValue: 36.3,
    heatingValueUnit: 'MJ/L',
    co2EF: 75100,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:B-A유',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 고체 연료 (Solid Fuels) ==========
  {
    name: 'Anthracite (Domestic)',
    translationKey: 'anthracite',
    units: ['kg'],
    factors: { 'kg': 1.92032 }, // 19.4 * (98300 + 10*21 + 1.5*310) / 10^6
    netHeatingValue: 19.4,
    heatingValueUnit: 'MJ/kg',
    co2EF: 98300,
    ch4EF: 10,  // 제조업 부문 (에너지산업:1, 제조업:10)
    n2oEF: 1.5,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:16',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  {
    name: 'Bituminous Coal',
    translationKey: 'coalBituminous',
    units: ['kg'],
    factors: { 'kg': 2.25199 }, // 23.7 * (94600 + 10*21 + 1.5*310) / 10^6
    netHeatingValue: 23.7,
    heatingValueUnit: 'MJ/kg',
    co2EF: 94600,
    ch4EF: 10,  // 제조업 부문 (에너지산업:1, 제조업:10)
    n2oEF: 1.5,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:19',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  {
    name: 'Bituminous Coal (Raw Materials)',
    translationKey: 'coalBituminousRaw',
    units: ['kg'],
    factors: { 'kg': 2.65849 }, // 28.0 * (94600 + 10*21 + 1.5*310) / 10^6
    netHeatingValue: 28.0,
    heatingValueUnit: 'MJ/kg',
    co2EF: 94600,
    ch4EF: 10,  // 제조업 부문 (에너지산업:1, 제조업:10)
    n2oEF: 1.5,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:20',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  {
    name: 'Imported Anthracite (Fuel)',
    translationKey: 'anthraciteImportFuel',
    units: ['kg'],
    factors: { 'kg': 2.02919 }, // 20.5 * (98300 + 10*21 + 1.5*310) / 10^6
    netHeatingValue: 20.5,
    heatingValueUnit: 'MJ/kg',
    co2EF: 98300,
    ch4EF: 10,  // 제조업 부문 (에너지산업:1, 제조업:10)
    n2oEF: 1.5,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:17',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  {
    name: 'Imported Anthracite (Raw Materials)',
    translationKey: 'anthraciteImportRaw',
    units: ['kg'],
    factors: { 'kg': 2.44490 }, // 24.7 * (98300 + 10*21 + 1.5*310) / 10^6
    netHeatingValue: 24.7,
    heatingValueUnit: 'MJ/kg',
    co2EF: 98300,
    ch4EF: 10,  // 제조업 부문 (에너지산업:1, 제조업:10)
    n2oEF: 1.5,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:18',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  {
    name: 'Sub-bituminous Coal',
    translationKey: 'subBituminousCoal',
    units: ['kg'],
    factors: { 'kg': 1.92516 }, // 19.9 * (96100 + 10*21 + 1.5*310) / 10^6
    netHeatingValue: 19.9,
    heatingValueUnit: 'MJ/kg',
    co2EF: 96100,
    ch4EF: 10,  // 제조업 부문 (에너지산업:1, 제조업:10)
    n2oEF: 1.5,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:21',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  {
    name: 'Coke',
    translationKey: 'cokeStationary',
    units: ['kg'],
    factors: { 'kg': 3.09641 }, // 28.9 * (107000 + 3*21 + 0.1*310) / 10^6
    netHeatingValue: 28.9,
    heatingValueUnit: 'MJ/kg',
    co2EF: 107000,
    ch4EF: 3,  // 제조업 부문 (에너지산업:1, 제조업:3)
    n2oEF: 0.1,  // 제조업 부문 (에너지산업:0.1, 제조업:0.1)
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:22',
    source: '온실가스 배출권거래제 지침 (2024) - 제조업 부문',
  },
  // ========== 기타 연료 (Additional Fuels from CSV 23-30) ==========
  {
    name: 'Naphtha',
    translationKey: 'naphtha',
    units: ['liters'],
    factors: { 'liters': 2.19938 },
    netHeatingValue: 29.9,
    heatingValueUnit: 'MJ/L',
    co2EF: 73300,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:23',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Solvent',
    translationKey: 'solvent',
    units: ['liters'],
    factors: { 'liters': 2.23027 },
    netHeatingValue: 30.3,
    heatingValueUnit: 'MJ/L',
    co2EF: 73300,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:24',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Jet Fuel (Aviation)',
    translationKey: 'jetFuel',
    units: ['liters'],
    factors: { 'liters': 2.38133 },
    netHeatingValue: 33.9,
    heatingValueUnit: 'MJ/L',
    co2EF: 70000,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:25',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Asphalt',
    translationKey: 'asphalt',
    units: ['kg'],
    factors: { 'kg': 3.17324 },
    netHeatingValue: 39.2,
    heatingValueUnit: 'MJ/kg',
    co2EF: 80700,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:26',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Lubricating Oil',
    translationKey: 'lubricatingOil',
    units: ['liters'],
    factors: { 'liters': 2.74536 },
    netHeatingValue: 37.3,
    heatingValueUnit: 'MJ/L',
    co2EF: 73300,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:27',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Petroleum Coke',
    translationKey: 'petroleumCoke',
    units: ['kg'],
    factors: { 'kg': 3.34172 },
    netHeatingValue: 34.2,
    heatingValueUnit: 'MJ/kg',
    co2EF: 97500,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:28',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'By-product Fuel Oil No.1',
    translationKey: 'byproductFuelOil1',
    units: ['liters'],
    factors: { 'liters': 2.49736 },
    netHeatingValue: 34.6,
    heatingValueUnit: 'MJ/L',
    co2EF: 71900,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:29',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'By-product Fuel Oil No.2',
    translationKey: 'byproductFuelOil2',
    units: ['liters'],
    factors: { 'liters': 2.92856 },
    netHeatingValue: 37.7,
    heatingValueUnit: 'MJ/L',
    co2EF: 77400,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:30',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'B-B Oil',
    translationKey: 'bbOil',
    units: ['liters'],
    factors: { 'liters': 2.91327 },
    netHeatingValue: 38.0,
    heatingValueUnit: 'MJ/L',
    co2EF: 76400,
    ch4EF: 3,
    n2oEF: 0.6,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:12',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
];

export const MOBILE_FUELS: CO2eFactorFuel[] = [
  // ========== 도로 운송 (Road Transportation) ==========
  {
    name: 'Gasoline (Petrol)',
    translationKey: 'gasoline',
    units: ['liters', 'gal'],
    factors: { 'liters': 2.19807, 'gal': 8.33069 }, // gal = 2.19807 × 3.79
    netHeatingValue: 30.4,
    heatingValueUnit: 'MJ/L',
    co2EF: 69300,
    ch4EF: 25,
    n2oEF: 8,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:이동-휘발유',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Diesel',
    translationKey: 'diesel',
    units: ['liters', 'gal'],
    factors: { 'liters': 2.65383, 'gal': 10.0580 }, // gal = 2.65383 × 3.79
    netHeatingValue: 35.2,
    heatingValueUnit: 'MJ/L',
    co2EF: 74100,
    ch4EF: 4,
    n2oEF: 3.9,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:이동-경유',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'LPG (Vehicle)',
    translationKey: 'lpgVehicle',
    units: ['liters', 'kg', 'gal'],
    factors: { 'liters': 1.603, 'kg': 2.94600, 'gal': 6.07537 }, // gal = 1.603 × 3.79
    netHeatingValue: 45.7,
    heatingValueUnit: 'MJ/kg',
    co2EF: 63100,
    ch4EF: 62,
    n2oEF: 0.2,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:이동-LPG',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'CNG / LNG (Vehicle)',
    translationKey: 'cngVehicle',
    units: ['Nm3'],
    factors: { 'Nm3': 2.29362 },
    netHeatingValue: 38.9,
    heatingValueUnit: 'MJ/Nm3',
    co2EF: 56100,
    ch4EF: 92,
    n2oEF: 3.0,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:이동-CNG',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
];


// ============================================================================
// Process Emissions - CSV 기반 (GHG_EmissionFactor.csv 63-107행)
// ============================================================================
// 출처: 온실가스 배출권거래제 지침 [별표 6] 공정배출원 배출계수
// ============================================================================

export const PROCESS_MATERIALS: CO2eFactorFuel[] = [
  // ========== 석회 생산 (CSV 66-67) ==========
  {
    name: 'Quickite Lime (생석회)',
    translationKey: 'quicklime',
    units: ['tonnes'],
    factors: { 'tonnes': 750 },
    co2EF: 750,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:66',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Dolomitic Lime (고토석회/경소백운석)',
    translationKey: 'dolomiticLime',
    units: ['tonnes'],
    factors: { 'tonnes': 770 },
    co2EF: 770,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:67',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 탄산염 사용 (CSV 69-75) ==========
  {
    name: 'Limestone (석회석, CaCO₃)',
    translationKey: 'limestone',
    units: ['tonnes'],
    factors: { 'tonnes': 440 },
    co2EF: 440,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:69',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Magnesite (마그네사이트, MgCO₃)',
    translationKey: 'magnesite',
    units: ['tonnes'],
    factors: { 'tonnes': 522 },
    co2EF: 522,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:70',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Dolomite (백운석)',
    translationKey: 'dolomite',
    units: ['tonnes'],
    factors: { 'tonnes': 477 },
    co2EF: 477,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:71',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Siderite (능철광, FeCO₃)',
    translationKey: 'siderite',
    units: ['tonnes'],
    factors: { 'tonnes': 380 },
    co2EF: 380,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:72',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Ankerite (철백운석)',
    translationKey: 'ankerite',
    units: ['tonnes'],
    factors: { 'tonnes': 442 },
    co2EF: 442,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:73',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Rhodochrosite (망간광, MnCO₃)',
    translationKey: 'rhodochrosite',
    units: ['tonnes'],
    factors: { 'tonnes': 383 },
    co2EF: 383,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:74',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Soda Ash (소다회, Na₂CO₃)',
    translationKey: 'sodaAsh',
    units: ['tonnes'],
    factors: { 'tonnes': 415 },
    co2EF: 415,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:75',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 유리 생산 (CSV 77-86) ==========
  {
    name: 'Flat Glass (판유리)',
    translationKey: 'flatGlass',
    units: ['tonnes'],
    factors: { 'tonnes': 210 },
    co2EF: 210,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:77',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Container Glass (유리용기)',
    translationKey: 'containerGlass',
    units: ['tonnes'],
    factors: { 'tonnes': 210 },
    co2EF: 210,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:78-79',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Continuous Filament Glass Fiber (유리장섬유)',
    translationKey: 'continuousGlassFiber',
    units: ['tonnes'],
    factors: { 'tonnes': 190 },
    co2EF: 190,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:80',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Glass Wool (유리단섬유)',
    translationKey: 'glassWool',
    units: ['tonnes'],
    factors: { 'tonnes': 250 },
    co2EF: 250,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:81',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'CRT Glass Panel (브라운관 Panel)',
    translationKey: 'crtGlassPanel',
    units: ['tonnes'],
    factors: { 'tonnes': 180 },
    co2EF: 180,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:82',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'CRT Glass Funnel (브라운관 Funnel)',
    translationKey: 'crtGlassFunnel',
    units: ['tonnes'],
    factors: { 'tonnes': 130 },
    co2EF: 130,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:83',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Household Glass Products (가정용 유리제품)',
    translationKey: 'householdGlass',
    units: ['tonnes'],
    factors: { 'tonnes': 100 },
    co2EF: 100,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:84',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Laboratory Glassware (실험용기/약병)',
    translationKey: 'laboratoryGlassware',
    units: ['tonnes'],
    factors: { 'tonnes': 30 },
    co2EF: 30,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:85',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Lighting Glass (전등용 유리)',
    translationKey: 'lightingGlass',
    units: ['tonnes'],
    factors: { 'tonnes': 200 },
    co2EF: 200,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:86',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 카바이드 생산 (CSV 88-89) ==========
  {
    name: 'Calcium Carbide (칼슘카바이드, CaC₂)',
    translationKey: 'calciumCarbide',
    units: ['tonnes'],
    factors: { 'tonnes': 1090 },
    co2EF: 1090,
    ch4EF: 0,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:88',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Silicon Carbide (실리콘카바이드, SiC)',
    translationKey: 'siliconCarbide',
    units: ['tonnes'],
    factors: { 'tonnes': 2863.6 },
    co2EF: 2620,
    ch4EF: 11.6,
    gwpCH4: 21,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:89',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 소다회 생산 (CSV 91) ==========
  {
    name: 'Soda Ash Production (소다회 생산)',
    translationKey: 'sodaAshProduction',
    units: ['tonnes'],
    factors: { 'tonnes': 138 },
    co2EF: 138,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:91',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 합금철 생산 (CSV 93-100) ==========
  {
    name: 'Ferroalloy (Si 45%)',
    translationKey: 'ferroalloySi45',
    units: ['tonnes'],
    factors: { 'tonnes': 2500 },
    co2EF: 2500,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:93',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Ferroalloy (Si 65%)',
    translationKey: 'ferroalloySi65',
    units: ['tonnes'],
    factors: { 'tonnes': 3600 },
    co2EF: 3600,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:94',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Ferroalloy (Si 75%)',
    translationKey: 'ferroalloySi75',
    units: ['tonnes'],
    factors: { 'tonnes': 4000 },
    co2EF: 4000,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:95',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Ferroalloy (Si 90%)',
    translationKey: 'ferroalloySi90',
    units: ['tonnes'],
    factors: { 'tonnes': 4800 },
    co2EF: 4800,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:96',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Ferromanganese (C 7%)',
    translationKey: 'ferromanganeseC7',
    units: ['tonnes'],
    factors: { 'tonnes': 1300 },
    co2EF: 1300,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:97',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Ferromanganese (C 1%)',
    translationKey: 'ferromanganeseC1',
    units: ['tonnes'],
    factors: { 'tonnes': 1500 },
    co2EF: 1500,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:98',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Silicomanganese (실리코망간)',
    translationKey: 'silicomanganese',
    units: ['tonnes'],
    factors: { 'tonnes': 1400 },
    co2EF: 1400,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:99',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Silicon Metal (실리콘메탈)',
    translationKey: 'siliconMetal',
    units: ['tonnes'],
    factors: { 'tonnes': 5000 },
    co2EF: 5000,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:100',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 아연 생산 (CSV 102-105) ==========
  {
    name: 'Zinc Production (Unspecified Smelting)',
    translationKey: 'zincUnspecified',
    units: ['tonnes'],
    factors: { 'tonnes': 1720 },
    co2EF: 1720,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:102',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Zinc Production (Waelz Kiln)',
    translationKey: 'zincWaelzKiln',
    units: ['tonnes'],
    factors: { 'tonnes': 3660 },
    co2EF: 3660,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:103',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Zinc Production (Electrothermic)',
    translationKey: 'zincElectrothermic',
    units: ['tonnes'],
    factors: { 'tonnes': 0 },
    co2EF: 0,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:104',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Zinc Production (Pyrometallurgical)',
    translationKey: 'zincPyrometallurgical',
    units: ['tonnes'],
    factors: { 'tonnes': 430 },
    co2EF: 430,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:105',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 납 생산 (CSV 107) ==========
  {
    name: 'Lead Production (납 생산)',
    translationKey: 'leadProduction',
    units: ['tonnes'],
    factors: { 'tonnes': 5200 },
    co2EF: 5200,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:107',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
];


// GWP values sourced from IPCC AR5
export const FUGITIVE_GASES: Refrigerant[] = [
  { name: 'HFC-134a (Refrigerant)', translationKey: 'hfc134a', gwp: 1430 },
  { name: 'R-404A (Refrigerant)', translationKey: 'r404a', gwp: 3922 },
  { name: 'R-410A (Refrigerant)', translationKey: 'r410a', gwp: 2088 },
  { name: 'R-22 (HCFC-22, Refrigerant)', translationKey: 'r22', gwp: 1810 },
  { name: 'SF6 (from electrical equipment)', translationKey: 'sf6', gwp: 23500 },
];

// ============================================================================
// Waste Incineration - CSV 기반 (GHG_EmissionFactor.csv 109-140행)
// ============================================================================
// 출처: 온실가스 배출권거래제 지침 [별표 6] 폐기물 소각 배출계수
// 단위: tCO2/t-Waste, tCH4/t-Waste, tN2O/t-Waste
// ============================================================================

export const WASTE_SOURCES: CO2eFactorFuel[] = [
  // ========== 고상 생활폐기물 (CSV 115-125) ==========
  {
    name: 'Paper Waste (종이류)',
    translationKey: 'wasteHouseholdPaper',
    units: ['tonnes'],
    factors: { 'tonnes': 31.35 },
    co2EF: 15.17,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:115',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Textile Waste (섬유류)',
    translationKey: 'wasteHouseholdTextile',
    units: ['tonnes'],
    factors: { 'tonnes': 309.34 },
    co2EF: 293.12,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:116',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Food Waste (음식물류)',
    translationKey: 'wasteHouseholdFood',
    units: ['tonnes'],
    factors: { 'tonnes': 16.28 },
    co2EF: 0,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:117',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Wood Waste (나무류)',
    translationKey: 'wasteHouseholdWood',
    units: ['tonnes'],
    factors: { 'tonnes': 16.28 },
    co2EF: 0,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:118',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Garden/Park Waste (정원 및 공원 폐기물류)',
    translationKey: 'wasteHouseholdGarden',
    units: ['tonnes'],
    factors: { 'tonnes': 16.28 },
    co2EF: 0,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:119',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Diapers (기저귀)',
    translationKey: 'wasteHouseholdDiapers',
    units: ['tonnes'],
    factors: { 'tonnes': 118.87 },
    co2EF: 102.59,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:120',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Rubber/Leather Waste (고무 피혁류)',
    translationKey: 'wasteHouseholdRubber',
    units: ['tonnes'],
    factors: { 'tonnes': 428.68 },
    co2EF: 412.42,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:121',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Plastic Waste - Household (플라스틱류)',
    translationKey: 'wasteHouseholdPlastic',
    units: ['tonnes'],
    factors: { 'tonnes': 2764.28 },
    co2EF: 2748,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:122',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Metal Waste (금속류)',
    translationKey: 'wasteHouseholdMetal',
    units: ['tonnes'],
    factors: { 'tonnes': 3680.28 },
    co2EF: 3664,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:123',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Glass Waste (유리류)',
    translationKey: 'wasteHouseholdGlass',
    units: ['tonnes'],
    factors: { 'tonnes': 3680.28 },
    co2EF: 3664,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:124',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Other Household Waste (기타 생활폐기물)',
    translationKey: 'wasteHouseholdOther',
    units: ['tonnes'],
    factors: { 'tonnes': 115.21 },
    co2EF: 98.93,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:125',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 고상 사업장폐기물 (CSV 126-135) ==========
  {
    name: 'Industrial Food Waste (사업장 음식물류)',
    translationKey: 'wasteIndustrialFood',
    units: ['tonnes'],
    factors: { 'tonnes': 40.51 },
    co2EF: 0,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:126',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Industrial Textile Waste (사업장 폐섬유류)',
    translationKey: 'wasteIndustrialTextile',
    units: ['tonnes'],
    factors: { 'tonnes': 228.10 },
    co2EF: 187.60,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:127',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Industrial Wood Waste (사업장 폐목재류)',
    translationKey: 'wasteIndustrialWood',
    units: ['tonnes'],
    factors: { 'tonnes': 40.51 },
    co2EF: 0,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:128',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Industrial Paper Waste (사업장 폐지류)',
    translationKey: 'wasteIndustrialPaper',
    units: ['tonnes'],
    factors: { 'tonnes': 54.03 },
    co2EF: 13.52,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:129',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Industrial Plastic/Solvent Waste (사업장 플라스틱류)',
    translationKey: 'wasteIndustrialPlastic',
    units: ['tonnes'],
    factors: { 'tonnes': 2385.47 },
    co2EF: 2345.00,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:130',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Industrial Synthetic Rubber Waste (사업장 폐합성고무)',
    translationKey: 'wasteIndustrialRubber',
    units: ['tonnes'],
    factors: { 'tonnes': 333.52 },
    co2EF: 293.00,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:131',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Construction & Demolition Waste (건설 및 파쇄 잔재물)',
    translationKey: 'wasteIndustrialConstruction',
    units: ['tonnes'],
    factors: { 'tonnes': 216.38 },
    co2EF: 175.87,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:132',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Other Industrial Waste (기타 사업장 폐기물)',
    translationKey: 'wasteIndustrialOther',
    units: ['tonnes'],
    factors: { 'tonnes': 44.47 },
    co2EF: 3.96,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:133',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Wastewater Sludge (폐수 슬러지)',
    translationKey: 'wasteIndustrialSludge',
    units: ['tonnes'],
    factors: { 'tonnes': 40.51 },
    co2EF: 0,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:134',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Medical Waste (의료폐기물)',
    translationKey: 'wasteIndustrialMedical',
    units: ['tonnes'],
    factors: { 'tonnes': 278.67 },
    co2EF: 238.16,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:135',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 하수 슬러지 (CSV 136) ==========
  {
    name: 'Sewage Sludge (하수 슬러지)',
    translationKey: 'wasteSewageSludge',
    units: ['tonnes'],
    factors: { 'tonnes': 186.05 },
    co2EF: 0,
    ch4EF: 76.3,
    n2oEF: 595.0,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:136',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 액상 폐기물 (CSV 137-138) ==========
  {
    name: 'Liquid Household Waste (액상 생활폐기물)',
    translationKey: 'wasteLiquidHousehold',
    units: ['tonnes'],
    factors: { 'tonnes': 2947.48 },
    co2EF: 2931.20,
    ch4EF: 6.1,
    n2oEF: 52.1,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:137',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Liquid Industrial Waste (액상 사업장폐기물)',
    translationKey: 'wasteLiquidIndustrial',
    units: ['tonnes'],
    factors: { 'tonnes': 2971.71 },
    co2EF: 2931.20,
    ch4EF: 13.9,
    n2oEF: 129.7,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:138',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  // ========== 기상 폐기물 (CSV 139-140) ==========
  {
    name: 'Waste Gas (폐가스)',
    translationKey: 'wasteGas',
    units: ['tonnes'],
    factors: { 'tonnes': 2856.26 },
    co2EF: 2851.20,
    ch4EF: 193.5,
    n2oEF: 3.87,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:139',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
  {
    name: 'Biogas (Methane) (바이오가스)',
    translationKey: 'wasteBiogas',
    units: ['tonnes'],
    factors: { 'tonnes': 2758.85 },
    co2EF: 2751.80,
    ch4EF: 252.0,
    n2oEF: 5.04,
    gwpCH4: 21,
    gwpN2O: 310,
    isVerified: true,
    csvLineRef: 'GHG_EmissionFactor.csv:140',
    source: '온실가스 배출권거래제 지침 (2024)',
  },
];
